---
title: "Access to green space in the AV"
author: "Alicia Vo"
date: "2025-10-01"
output: html_document
---

```{r}
#install packages if not already installed
packages <- c("dplyr","data.table","tidycensus","sf","DBI","RPostgres","stringr","tidyr","tigris","usethis")  

install_packages <- packages[!(packages %in% installed.packages()[,"Package"])] 

if(length(install_packages) > 0) { 
  install.packages(install_packages) 
  
} else { 
  
  print("All required packages are already installed.") 
} 

for(pkg in packages){ 
  library(pkg, character.only = TRUE) 
} 

options(scipen=999)

###### SET UP WORKSPACE #######
# create connection for rda database
source("W:\\RDA Team\\R\\credentials_source.R")
conn <- connect_to_db("rda_shared_data")

# set source for Weighted Average Functions & SWANA Ancestry scripts
source("W:/RDA Team/R/Github/RDA Functions/LF/RDA-Functions/Cnty_St_Wt_Avg_Functions.R")
source("W:/RDA Team/R/Github/RDA Functions/LF/RDA-Functions/SWANA_Ancestry_List.R")


# update variables used throughout each year
curr_yr <- 2023  # NLCD and ACS year
rc_yr <- '2025'
rc_schema <- 'v7'

# Check that variables in vars_list_dp05 used in WA fx haven't changed --------
# select acs race/eth pop variables: All AIAN/PacIsl, NH Alone White/Black/Asian/Other, NH Two+, Latinx of any race
## the variables MUST BE in this order:
vars_list_dp05 <-      c('total_'= "DP05_0001",
                         'aian_' = "DP05_0071",
                         'pacisl_' = "DP05_0073",
                         'latino_' = "DP05_0076",
                         'nh_white_' = "DP05_0082",
                         'nh_black_' = "DP05_0083",
                         'nh_asian_' = "DP05_0085",
                         'nh_other_' = "DP05_0087",
                         'nh_twoormor_' = "DP05_0088")

race_mapping <- data.frame(
  name = unlist(vars_list_dp05),
  race = names(vars_list_dp05),
  stringsAsFactors = FALSE
)

dp05_curr <- load_variables(curr_yr, "acs5/profile", cache = TRUE) %>% 
  select(-c(concept)) %>% 
  filter(name %in% vars_list_dp05) %>%
  left_join(race_mapping, by="name") %>%
  mutate(rc_races = paste0(race, "pop"), 
         name = tolower(name),            # get all DP05 vars
         label <- gsub("Estimate!!|HISPANIC OR LATINO AND RACE!!", "", label))        

# Grab SPA-tract xwalk so that we can get all tracts within SPA 1 which we are using as our AV geography. Census tracts are 2023.
spa <- dbGetQuery(conn, "SELECT * FROM crosswalks.lacounty_health_district_spa_tract_2022")%>%
  filter(spa_num==1)

##### 1. GET INDICATOR DATA ######
# You MUST load indicator data using these table/column names (ind_df with cols subid / indicator) in order for WA functions to work
ind_df_all <- dbGetQuery(conn, paste0("SELECT ct_geoid AS sub_id, median AS indicator FROM built_environment.nlcd_tract_impervious_land_", curr_yr))

ind_df <- ind_df_all %>% filter(sub_id %in% spa$ct_geoid)
```

```{r}
###### DEFINE VALUES FOR FUNCTIONS ###
# set values for weighted average functions - You may need to update these
subgeo <- c('tract')             # define your sub geolevel: tract (unless the WA functions are adapted for a different subgeo)
targetgeolevel <- c('antelope_valley')      # define your target geolevel
survey <- "acs5"                 # define which Census survey you want
pop_threshold = 0              # define population threshold for screening

##### GET SUB GEOLEVEL POP DATA ###
pop <- update_detailed_table(vars = vars_list_dp05, yr = curr_yr, srvy = survey)  # subgeolevel pop

```

