```{r}
source("./visual_fx.R")

con_ctc<- connect_to_db("cancel_the_contract")

dict_sp <- dict_sp %>% filter(filename == "Police Hit Rate AVUHSD_pie.png")
title_text <- dict_sp$title

df<-dbGetQuery(con_ctc, "SELECT contraband_evidence_discovered_none as label, rate FROM analysis_stops_hitrate_avuhsd")

df_subset <- df %>%
  mutate(label = ifelse(label=="0", "Contrabando", "Sin contrabando"))

indicator <- "Police Hit Rate AVUHSD"
```

## Run these chunks for the Spanish chart
```{r}
pie_chart_sp <- function(df, indicator, title_text) {

  width <- 7.5   # inches
  height <- 7.5  # inches  

  # Adjust width based on title length
  # title_length <- nchar(title_text)
  title_text <- stringr::str_wrap(title_text, width = width * 20)
  title_text <- stringr::str_replace_all(title_text, "\n", "<br>")

  subtitle_text <- ""
  
  caption_text<-paste0("Recurso: ",dict$source[dict$indicator_short==indicator]," data, ", dict$year[dict$indicator_short==indicator],". ",dict$race_note[dict$indicator_short==indicator]) 

  # caption_text <- str_wrap(caption_text, width = width * 15)

  grey_label_name <- df$label[which.min(df$rate)]
  
  # ---- build plot ----
  final_visual <- ggplot(df, aes(x = "", y = rate, fill = label)) +
    geom_col(color = "white", width = 1, show.legend = TRUE) +
    coord_polar(theta = "y") +
    geom_text(
      aes(
        label = paste0(round(rate, 1), "%"),
        colour = ifelse(label == grey_label_name, black, "white"),
        family = ifelse(label == grey_label_name, "gillsans", "gillsans_bold")
      ),
      position = position_stack(vjust = 0.5),
      # family = font_bar_label,
      size = 11,
      show.legend = FALSE
    ) +

    scale_fill_manual(values = c(textgrey, teal), guide = guide_legend(reverse = FALSE)) +
    scale_colour_identity() +
    labs(title = str_wrap(title_text,100),
         subtitle = subtitle_text, 
         caption = caption_text, fill = "") +
    theme_minimal() +
    theme(
      axis.text = element_blank(),
      axis.title = element_blank(),
      panel.grid = element_blank(),
      axis.ticks = element_blank(),
      plot.title = ggtext::element_markdown(
        hjust = 0,
        size = 30,
        family = font_title,
        colour = black,
        lineheight = .4
      ),
      plot.subtitle = element_text(hjust = 0, size = 25, family = font_subtitle, colour = black),
      plot.caption = element_text(hjust = 0, size = 18, family = font_caption, colour = black, lineheight = 0.59),
      plot.background = element_rect(fill = "white", color = NA),

      legend.text = element_text(size = 20, family = font_axis_label, colour = black),
      legend.position = "right",
      plot.margin = margin(10, 40, 10, 10)

    )

  # ---- export ----
  export_dir <- here::here("Visuals", "Exports SP")
  dir.create(export_dir, recursive = TRUE, showWarnings = FALSE)
  outfile <- file.path(export_dir, paste0(indicator, "_pie_sp.png"))

  ragg::agg_png(outfile, width = width, height = height, units = "in", res = 300)
  print(final_visual)
  dev.off()

  return(final_visual)
}

pie_chart_sp(df_subset, indicator, title_text) 
```

## Run these chunks for the English chart
```{r}
df_subset <- df %>%
  mutate(label = ifelse(label=="0", "Contraband", "No contraband"))

indicator <- "Police Hit Rate AVUHSD"
title_text <- "The vast majority of LASD searches of AVUHSD students result in no contraband"
```

```{r}
pie_chart <- function(df, indicator, title_text) {

  width <- 4   # inches
  height <- 4  # inches  

  # Adjust width based on title length
  title_length <- nchar(title_text)
  # title_text <- str_wrap(title_text, width = width * 10)
  
  subtitle_text <- ""
  
  caption_text<-paste0("Source: Catalyst California calculations of ",dict$source[dict$indicator_short==indicator]," data, ", dict$year[dict$indicator_short==indicator],". ",dict$race_note[dict$indicator_short==indicator]) 

  # caption_text <- str_wrap(caption_text, width = width * 15)

  grey_label_name <- df$label[which.min(df$rate)]
  
  # ---- build plot ----
  final_visual <- ggplot(df, aes(x = "", y = rate, fill = label)) +
    geom_col(color = "white", width = 1, show.legend = TRUE) +
    coord_polar(theta = "y") +
    # center labels inside slices
    # geom_text(aes(label = paste0(round(rate, 1), "%")),
    #           position = position_stack(vjust = 0.5),
    #           family = font_bar_label,
    #           size = 6,
    #           colour = black) +
    geom_text(
      aes(
        label = paste0(round(rate, 1), "%"),
        colour = ifelse(label == grey_label_name, black, "white"),
        family = ifelse(label == grey_label_name, "gillsans", "gillsans_bold")
      ),
      position = position_stack(vjust = 0.5),
      # family = font_bar_label,
      size = 12,
      show.legend = FALSE
    ) +

    scale_fill_manual(values = c(textgrey, teal), guide = guide_legend(reverse = FALSE)) +
    scale_colour_identity() +
    labs(title = title_text, subtitle = subtitle_text, caption = caption_text, fill = "") +
    theme_minimal() +
    theme(
      axis.text = element_blank(),
      axis.title = element_blank(),
      panel.grid = element_blank(),
      axis.ticks = element_blank(),

      plot.title = element_text(hjust = 0, size = 30, family = font_title, colour = black),
      plot.subtitle = element_text(hjust = 0, size = 25, family = font_subtitle, colour = black),
      plot.caption = element_text(hjust = 0, size = 18, family = font_caption, colour = black, lineheight = 0.59),
      plot.background = element_rect(fill = "white", color = NA),

      legend.text = element_text(size = 18, family = font_axis_label, colour = black),
      legend.position = "right",
      plot.margin = margin(10, 40, 10, 10)

    )

  # ---- export ----
  export_dir <- here::here("Visuals", "Exports")
  dir.create(export_dir, recursive = TRUE, showWarnings = FALSE)
  outfile <- file.path(export_dir, paste0(indicator, "_pie.png"))

  ragg::agg_png(outfile, width = width, height = height, units = "in", res = 300)
  print(final_visual)
  dev.off()

  return(final_visual)
}

# pie_chart(df_subset, indicator, title_text) 
```