```{r}
source("./visual_fx.R")

con_ctc<- connect_to_db("cancel_the_contract")

df<-dbGetQuery(con_ctc, "SELECT * FROM analysis_stops_search_avuhsd")
               
               
               # WHERE reportingcategory_re IN ('nh_black', 'latinx', 'nh_white', 'student__disability', 'total')")


df <- df %>% mutate(label = reportingcategory_re)%>%
  race_recode()

indicator <- "Police Stops Search AVUHSD"
title_text <- "Law Enforcement Searches Black and Latinx Students during Stops far more than White Students"

```


```{r}

# rename 'rate' column for function and arrange by rate descending
  df<-df%>%
    rename_with(~ "rate", .cols = contains("rate"))
  
# Define max value
 max_y = 1.15 * max(df$rate)

 # Define annotation
 annotate_y = 1.12 * (df$rate[df$label=="Total"])
 
 # set total value
 total_value<- subset(df, label=="Total")$rate
 
 # Dynamically adjust dimensions of the output
 
 # Base width/height
 base_width <- 7   # inches
 base_height <- 5  # inches
 
 # Adjust height based on number of rows (bars)
 num_bars <- nrow(df %>% filter(label != "Total"))
 height <- base_height + 0.2 * num_bars  # each bar adds 0.2 inches
 
 # Adjust width based on title length
 title_length <- nchar(title_text)
 width <- base_width + 0.05 * title_length  # long titles get extra width
 
 ## Set up subtitle text: This will be from the data dictionary
 
 subtitle_text<-paste0(dict$indicator[dict$indicator_short==indicator])
 
 # # set caption text to use values from the data dictionary
 
 caption_text<-paste0("Source: Catalyst California calculations of ",dict$source[dict$indicator_short==indicator]," data, ", dict$year[dict$indicator_short==indicator],". ",dict$race_note[dict$indicator_short==indicator]) 
 
 
 
 wrap_width <- round(width * 12)
 caption_text <- str_wrap(caption_text, width = wrap_width)

 # Graph
 
  final_visual <-  ggplot(subset(df, label !='Total' ), aes(x= reorder(label, rate), y=rate)) +   
    geom_bar(stat="identity", position = position_dodge(0.7), show.legend = FALSE) +
    
    # define the bars
    
    geom_col(fill = teal) +
    
  # vertical line for Total %
    geom_hline(yintercept = subset(df, label =="Total")$rate, linetype = "dotted", color = black, size = 0.75) +    
   
    # label for vertical Total % line
    
    annotate(geom = "text",
             x = 1.0,
             y = subset(df, label=="Total")$rate,
             label = sprintf("Overall Rate: %.1f%%", subset(df, label == "Total")$rate),
             hjust =-0.1, vjust = 0,
             color = black, size =3.5, family = font_axis_label) +
    
    # bar labels
    
    geom_text(aes(label = paste0(round(rate, 1), "%")),
              family = font_bar_label, 
              hjust = -0.1,   # small negative number pushes text to the right of the bar
              vjust = 0.5,
              colour = "black",
              size =3.5) +
    
    labs(title = title_text,
         subtitle = str_wrap(subtitle_text, width = 80),
         caption=caption_text) + 
  
    scale_x_discrete(labels = function(label) str_wrap(label, width = 20)) +            # wrap long labels
    xlab("") +
    ylab("") +
    expand_limits(y = c(0, max_y))+
  coord_flip()

  
  # ---- Final graph theme ----
final_visual <- final_visual +
  theme_minimal(base_size = 12) +
  theme(
    legend.title = element_blank(),
    axis.text.y = element_text(size = rel(1.0), 
                               margin = margin(0, -10, 0, 0),
                               colour = black, family = font_axis_label),
    axis.text.x = element_blank(),
    plot.caption = element_text(hjust = 0, size = rel(0.7), colour = black, family = font_caption),
    plot.title = element_text(hjust = 0, size = rel(1.3), colour = black, family = font_title), 
    plot.subtitle = element_text(hjust = 0, size = rel(1.0), colour = black, family = font_subtitle),
    axis.ticks = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(size = 0.25),
    panel.grid.major.y = element_blank(),
    plot.margin = margin(10, 20, 40, 20)
  )
  
  
  final_visual

# ---- Export ----
export_dir <- here::here("Visuals", "Exports")
dir.create(export_dir, recursive = TRUE, showWarnings = FALSE)
outfile <- file.path(export_dir, paste0(indicator, "_singlebartot.png"))

ragg::agg_png(outfile, width = width, height = height, units = "in", res = 300)
print(final_visual)
dev.off()
  

  



```