---
title: ""
output:
  html_document:
    includes:
      in_header: "../header.html"
    mathjax: null
---

```{r, include=FALSE}
# Check if document is being run as a child, if yes don't apply styling again
is_child <- !is.null(knitr::opts_knit$get("parent.frame"))
if (is_child) {
  knitr::opts_chunk$set(include = FALSE)
}
```

```{r, include=FALSE}

# Set up (add any additional libraries you may need)-----------------------------

library(RPostgres)
library(devtools)
library(stringr)
library(dplyr)
library(tidyr)
library(flextable)
library(ggplot2)


# Visualization tools (optional!)-------------------------

#add function that better fits the tables to the page

FitFlextableToPage <- function(ft, pgwidth = 6.5){

  ft_out <- ft %>% autofit()

  ft_out <- width(ft_out, width = dim(ft_out)$widths*pgwidth /(flextable_dim(ft_out)$widths))
  return(ft_out)
}

# See "W:\Project\RJS\CTC\Github\JZ\cancel_the_contract\RDA Sense Making\sensemaking_jz.Rmd" for one ggplot and one flextable example
# if you want to visualize tables quickly

# See this script for examples of how to use the visual functions:
## W:\\Project\\RJS\CTC\\Github\\JZ\\cancel_the_contract\\Visuals\\visual_fx.R

# Guiding questions-------------------------

#1) What findings are you seeing that are interesting or surprising to you?
#2) What findings are you seeing that supplement OR contradict our narrative? 
#3) What additional questions do you have?
#4) What visualization ideas (chart types, figures to highlight, etc.) do you have? 

```

## JZ General notes

* General notes and observations outside of specific analyses

```{r}

#connect to postgres
source("W:\\RDA Team\\R\\credentials_source.R")
con <- connect_to_db("cancel_the_contract")
con_shared <- connect_to_db("rda_shared_data")

# data dictionary
dict<-dbGetQuery(con, "SELECT * FROM data_dictionary")


# School analysis tables
expulsions<-dbGetQuery(con, "SELECT * FROM analysis_expulsions") #JZ
grad<-dbGetQuery(con, "SELECT * FROM analysis_graduation") # JZ
suspension<-dbGetQuery(con, "SELECT * FROM analysis_suspensions") # JZ


# RIPA analysis tables: SPA 1

stops_age<-dbGetQuery(con, "SELECT * FROM analysis_stops_age") # AV
stops_race<-dbGetQuery(con, "SELECT * FROM analysis_stops_race") # AV
stops_age_race<-dbGetQuery(con, "SELECT * FROM analysis_stops_age_by_race") # AV

stops_stops_reason_age<-dbGetQuery(con, "SELECT * FROM analysis_stops_reason_age") # CR
stops_stops_reason_age_race<-dbGetQuery(con, "SELECT * FROM analysis_stops_reason_age_race") # CR


# RIPA analysis tables: AVUHSD
stops_disability_avuhsd<-dbGetQuery(con, "SELECT * FROM analysis_stops_disability_avuhsd") # AV
stops_race_avuhsd<-dbGetQuery(con, "SELECT * FROM analysis_stops_race_avuhsd") # AV

stops_reason_avuhsd<-dbGetQuery(con, "SELECT * FROM analysis_stops_reason_avuhsd")  # CR
stops_reason_rs_avuhsd<-dbGetQuery(con, "SELECT * FROM analysis_stops_reason_rs_avuhsd") # CR
stops_reason_rs_codes_avuhsd<-dbGetQuery(con, "SELECT * FROM analysis_stops_reason_rs_codes_avuhsd") # CR

stops_result_avuhsd<-dbGetQuery(con, "SELECT * FROM analysis_stops_result_avuhsd") # JZ


stops_reason_reason_narrative_avuhsd<-dbGetQuery(con, "SELECT * FROM analysis_stops_reason_and_narrative_avuhsd") # CR
stops_reason_narrative_avuhsd<-dbGetQuery(con, "SELECT * FROM analysis_stops_narrative_avuhsd") # CR


```

## Antelope Valley general demographics

* Notes
* Ideas about visualizations

```{r}

# AV Demographic tables

av_race<-dbGetQuery(con, "SELECT * FROM av_population_race")
av_age<-dbGetQuery(con, "SELECT * FROM av_population_age")


```

### Antelope Valley population by race

```{r}

title_text<-"The majority of residents in the AV are Latinx, White and Black"
subtitle_text<-"Population in Antelope Valley SPA 1"
caption_text<-paste0("Source: ",dict$source[dict$indicator_short=="Race"])

#graph

ggplot(av_race, aes(x = reorder(race, rate), y = rate))+
  geom_bar(stat = "identity", fill = "#362178") + #to create barplot
  geom_text(aes(label = paste0(round(rate,1), "%")), #add percentage labels within the bars
          vjust=.5, #center percentage within the bar
          hjust=0,
          size = 3,
          color = "black")+ 
  scale_x_discrete(labels = ~ str_wrap(as.character(.x), 5))+
  labs(title = title_text, 
       subtitle = subtitle_text,
       caption = caption_text,
       x = "", #labels to visual
       y = "") +
  theme_bw()+
  theme(axis.text.x = element_text(angle = 0, hjust =0.5), #sets x-axis labels to be horizontal
      legend.position ="none", #removes legend
      plot.title = element_text(hjust=0.5),
      plot.subtitle = element_text(hjust=0.5),
       plot.caption = element_text(hjust = 0))+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=0.5, size=12), #aesthetics of the barchart
        strip.background = element_rect(fill = "#362178"),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
panel.background = element_blank())+
  coord_flip()


```

### Antelope Valley population by age

```{r}

df<-av_age%>%
  mutate(rate=round(rate,1))%>%
  select(age_re, total, count, rate)

# ##Flextable for Age Group, Race##


  flextable(df) %>%
  set_caption('Antelope Valley SPA 1 Age Demographics') %>%
  theme_vanilla() %>%
  width(width=2,unit="in")
  
  
```

## AVUHSD general demographics

* Notes
* Ideas about visualizations

```{r}

# AVUHSD Enrollment Data

enrollment <- dbGetQuery(con_shared, "SELECT * FROM education.cde_multigeo_enrollment_census_day_2024_25")

# get Antelope Valley Union High School District enrollment
av_enrollment <- enrollment %>% filter(districtname == "Antelope Valley Union High" & charter == "ALL")%>%
  filter(grepl("RE_", reportingcategory))

# recode racial categories

av_enrollment<-av_enrollment%>%
  mutate(reportingcategory_re=ifelse(reportingcategory %in% "RE_B", "nh_black",
                                     ifelse(reportingcategory %in% "RE_I", "nh_aian", 
                                            ifelse(reportingcategory %in% "RE_A", "nh_asian", 
                                                   ifelse(reportingcategory %in% "RE_F", "nh_filipino",  
                                                          ifelse(reportingcategory %in% "RE_H", "latinx", 
                                                                 ifelse(reportingcategory %in% "RE_D", "missing_race",
                                                                        ifelse(reportingcategory %in% "RE_P", "nh_nhpi",  
                                                                               ifelse(reportingcategory %in% "RE_T", "nh_twoormor",  
                                                                                      ifelse(reportingcategory %in% "RE_W", "nh_white", 
                                                                                             reportingcategory))))))))))%>%
  select(cdscode, districtname, reportingcategory_re, total_enr)

```

```{r}

# School analysis tables
expulsions<-dbGetQuery(con, "SELECT * FROM analysis_expulsions")
grad<-dbGetQuery(con, "SELECT * FROM analysis_graduation")
suspension<-dbGetQuery(con, "SELECT * FROM analysis_suspensions")

```

## Stop results in AVUHSD

```{r}
stops_result_avuhsd<-dbGetQuery(con, "SELECT * FROM analysis_stops_result_avuhsd") # JZ


```